# -*- coding: utf-8 -*-
"""programação-dinamica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MO8U_xpXi_OWijHC2aU-UQDlcNuva1PM
"""

def matrix_chain_order(p):
    n = len(p) - 1
    m = [[0 for _ in range(n)] for _ in range(n)]

    for L in range(2, n + 1):
        for i in range(n - L + 1):
            j = i + L - 1
            m[i][j] = float('inf')
            for k in range(i, j):
                q = m[i][k] + m[k + 1][j] + p[i] * p[k + 1] * p[j + 1]
                if q < m[i][j]:
                    m[i][j] = q

    return m[0][n-1]

dimensoes = [30, 35, 15, 5, 10, 20, 25]
print(matrix_chain_order(dimensoes))